version: "3.7"
services:
  resources-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.local
    ports:
      - 8001:5000
  
  resources-app-db:
    image: postgres:13
    volumes:
      - ./data/resources-db:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=resources-app
      - POSTGRES_PASSWORD=resources-app
      - POSTGRES_DB=resources-app
    ports:
     - 5432:5432